services:
  - type: web
    name: low-stock-alert-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: DATABASE_URL
        fromDatabase:
          name: low-stock-db
          property: connectionString
      - key: SALLA_CLIENT_ID
        sync: false
      - key: SALLA_CLIENT_SECRET
        sync: false
      - key: SALLA_CALLBACK_URL
        sync: false
      - key: SALLA_AUTHORIZATION_URL
        value: https://accounts.salla.sa/oauth2/auth
      - key: SALLA_TOKEN_URL
        value: https://accounts.salla.sa/oauth2/token
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

databases:
  - name: low-stock-db
    databaseName: stock_db
    user: stock_user
    plan: free
